---
language: python
python: "2.7"

env:
  - SITE=test.yml
  
before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
    # Check the role syntax.
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"

  # Run the role.
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
